UPDATE MENU SET ICON = 'SettingOutlined' WHERE ID_MENU = 1;
UPDATE MENU SET ICON = 'FolderOutlined' WHERE ID_MENU = 2;
UPDATE MENU SET ICON = 'FileSearchOutlined' WHERE ID_MENU = 3;
UPDATE MENU SET ICON = 'GoldOutlined' WHERE ID_MENU = 4;
UPDATE MENU SET ICON = 'UserOutlined' WHERE ID_MENU = 5;
UPDATE MENU SET ICON = 'FileDoneOutlined' WHERE ID_MENU = 6;
